version: '3.8'

services:
  node:
    build: .
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - mqtt-home
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  mongo:
    image: mongo:5.0.3
    restart: always
    networks:
      - mqtt-home
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    networks:
      - mqtt-home
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

volumes:
  mongo-data:

networks:
  mqtt-home:
    external: true
